### ISSUE TITLE
原WebAPI普通版本接口(http[s]: //api.xfyun.cn/v1/service/v1/tts) 不再对外开放

### ISSUE THREAD

**Issue by fuyuesong** [withsalt/IflySdk#1]
原接口后续可能会停用，能否帮忙优化成新接口，多谢！

https://www.xfyun.cn/doc/tts/online_tts/API.html

原WebAPI普通版本接口(http[s]: //api.xfyun.cn/v1/service/v1/tts) 不再对外开放，已经使用WebAPI普通版本的用户仍可使用，同时也欢迎体验新版流式接口并尽快完成迁移~

**Comment by withsalt** [comment]
我会尽快完成流式接口的编写。

**Comment by withsalt** [comment]
已经将TTS修改为流式接口。

**Comment by fuyuesong** [comment]
非常感谢！！！
