### ISSUE TITLE
出现connection without completing the close handshake 错误

### ISSUE THREAD

**Issue by daguda** [withsalt/IflySdk#2]
The remote party closed the WebSocket connection without completing the close handshake.

iat_Csharp_demo.zip 的例子一切正常

**Comment by withsalt** [comment]
我测试一下

**Comment by withsalt** [comment]
此错误是websocket断开了连接，你检查一下是不是网络环境的问题。我测试没出现错误。
或者能否提交详细错误说明？运行环境，怎么复现？

**Comment by withsalt** [comment]
已经优化ASR，应该不会出现此问题了。

**Comment by mzhou2018** [comment]
感谢回复。谢谢不出错了。但是结果还是没有输出。
![image](https://user-images.githubusercontent.com/44281076/67380038-562da700-f5bc-11e9-83d5-54bcd2236c79.png)

**Comment by mzhou2018** [comment]
> 已经优化ASR，应该不会出现此问题了。

谢谢
