### ISSUE TITLE
client.ReceiveAsync 接收数据BUG

### ISSUE THREAD

**Issue by sfltd** [withsalt/IflySdk#4]
目标框架改为.net standard2.0（或移植到.net framework4.8） 后不能一次性接收全部数据
TTSApi.cs 136行：
 var receive = await client.ReceiveAsync(new ArraySegment<byte>(array), CancellationToken.None);
不能一次性接收全部返回的数据，导致出错

**Comment by withsalt** [comment]
能否贴上调用代码或重现一下使用场景。我测试没有出现这个错误。

**Comment by sfltd** [comment]
重现：
1、将代码移植到.net  framework出现
2、.net  framework 项目引用 IflySdk(.Net Standard) 后调用时出现。（先将 IflySdk.dll 降级到.Net Standard2.0后在引用，因为Standard2.1无法引用到项目中）

**Comment by hadans** [comment]
我也遇到

**Comment by fuyuesong** [comment]
可以使用我的分支，接收不全，.net4.8无法使用，win7无法使用等问题都解决了，还增加了合成wav：https://github.com/fuyuesong/IflySdk

**Comment by withsalt** [comment]
> 可以使用我的分支，接收不全，.net4.8无法使用，win7无法使用等问题都解决了，还增加了合成wav：https://github.com/fuyuesong/IflySdk

感谢，能否pull request，我将修改合并进去。

**Comment by fuyuesong** [comment]
已经Pull request

**Comment by withsalt** [comment]
感谢，已Merge。
