### ISSUE TITLE
录音识别

### ISSUE THREAD

**Issue by Xhone** [withsalt/IflySdk#7]
您好!
    我运行录音识别的demo(ASRRecordDemo),在60s内麦克风没有接收到声音，就会报Recognition data failed. The remote party closed the WebSocket connection without completing the close handshake.
请问这个是通过websocket访问讯飞平台时，无法处理的异常吗？

**Comment by withsalt** [comment]
我测试一下。

**Comment by withsalt** [comment]
已修复。

**Comment by Xhone** [comment]
谢谢
