### ISSUE TITLE
ClientWebSocket在.NET 6和.NET Framework的版本上不一样，使用会报错

### ISSUE THREAD

**Issue by Happenss** [withsalt/IflySdk#8]
代码都是一样的，在.NET Framework中使用，ASRApi会因为ClientWebSocket的问题而报错。具体如下：远程方在没有完成关闭握手的情况下关闭了 WebSocket 连接。具体可能是底层 System.Net.WebSockets 的版本不一致导致的。
   我对WebSocket使用并不熟悉，希望大佬指教一下。

**Comment by Happenss** [comment]
问题出现在ASRApi第459行，异常判断内。断连判断的是异常的信息，但不同版本返回的信息不同，Framework异常是中文消息，不会进_ws.CloseAsync()的逻辑。

**Comment by withsalt** [comment]
好的。中文提示的啥来着？

**Comment by Happenss** [comment]
不好意思，我不常关注GitHub，回复的晚了。具体的 ex.Message 是：“远程方在没有完成关闭握手的情况下关闭了 WebSocket 连接。”
